[package]
name = "pwx"
version = "0.0.0"
build = "build.rs"

[dependencies]
rust-crypto = "0.2"
libc = "0.2"
matches = "0.1"
uuid = "0.1"
docopt = "0.6"
rustc-serialize = "0.3"
rpassword = "0.1"

[build-dependencies]
gcc = "0.3"

[[bin]]
name = "pwx"
doc = false

